### ISSUE TITLE
panic: runtime error: index out of range [2] with length 0

### ISSUE THREAD

**Issue by 1920853199** [bee/bee#225]
leechen@leechen:/var/local/go-blog$ bee generate appcode -tables=customer -driver=mysql -conn="root:123456@tcp(127.0.0.1:3306)/blog" -level=3
______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.11.0
2020/11/05 12:59:23 INFO     ▶ 0001 Using 'mysql' as 'SQLDriver'
2020/11/05 12:59:23 INFO     ▶ 0002 Using 'root:123456@tcp(127.0.0.1:3306)/blog' as 'SQLConn'
2020/11/05 12:59:23 INFO     ▶ 0003 Using 'customer' as 'Tables'
2020/11/05 12:59:23 INFO     ▶ 0004 Using '3' as 'Level'
2020/11/05 12:59:23 INFO     ▶ 0005 Analyzing database tables...
panic: runtime error: index out of range [2] with length 0

goroutine 1 [running]:
github.com/beego/bee/generate.extractIntSignness(0xc0000b93d3, 0x3, 0xc0000b93c8, 0x7)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:930 +0xbf
github.com/beego/bee/generate.(*MysqlDB).GetColumns(0x13a22e0, 0xc000302a90, 0xc000118a80, 0xc00017a300)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:481 +0xfb5
github.com/beego/bee/generate.getTableObjects(0xc000114960, 0x1, 0x1, 0xc000302a90, 0xef59a0, 0x13a22e0, 0x0, 0x1, 0x98)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:363 +0x1de
github.com/beego/bee/generate.gen(0xc000116410, 0x5, 0xc00012e240, 0x24, 0xc000233d07, 0xc000233ca8, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:316 +0x2dc
github.com/beego/bee/generate.GenerateAppcode(0xc000116410, 0x5, 0xc00012e240, 0x24, 0x131adf8, 0x1, 0xc000116418, 0x8, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/generate/g_appcode.go:295 +0x212
github.com/beego/bee/cmd/commands/generate.appCode(0x1350540, 0xc0000c0020, 0x5, 0x5, 0xc00003a184, 0x12)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/cmd/commands/generate/generate.go:158 +0x693
github.com/beego/bee/cmd/commands/generate.GenerateCode(0x1350540, 0xc0000c0020, 0x5, 0x5, 0x0)
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/cmd/commands/generate/generate.go:91 +0x285
main.main()
	/var/local/pkg/mod/github.com/beego/bee@v1.12.0/main.go:75 +0x2df

**Comment by mariux** [comment]
Closing.. I guess you meant opening this at https://github.com/beego/bee ;) please reopen there..
Thanks
